TUNED_PARAMS = {
    "flat": {
        "objective": "lambdarank",
        "n_estimators": 3000,
        "learning_rate": 0.04369,
        "num_leaves": 57,
        "min_child_samples": 69,
        "subsample": 0.8805,
        "colsample_bytree": 0.9574,
        "reg_alpha": 2.935e-06,
        "reg_lambda": 0.001326,
        "max_depth": 7,
        "min_split_gain": 0.02777,
        "random_state": 42,
        "n_jobs": -1,
    },
    "jumps": {
        "objective": "lambdarank",
        "n_estimators": 3000,
        "learning_rate": 0.04460,
        "num_leaves": 100,
        "min_child_samples": 63,
        "subsample": 0.7438,
        "colsample_bytree": 0.5903,
        "reg_alpha": 0.2719,
        "reg_lambda": 0.004538,
        "max_depth": 9,
        "min_split_gain": 0.06107,
        "random_state": 42,
        "n_jobs": -1,
    },
}

DEFAULT_PARAMS = {
    "objective": "lambdarank",
    "n_estimators": 3000,
    "learning_rate": 0.01,
    "num_leaves": 63,
    "min_child_samples": 20,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "random_state": 42,
    "n_jobs": -1,
}

CATBOOST_FLAT_PARAMS = {
    "loss_function": "YetiRank",
    "iterations": 3000,
    "learning_rate": 0.03,
    "depth": 6,
    "l2_leaf_reg": 3.0,
    "subsample": 0.8,
    "random_seed": 42,
    "verbose": 100,
    "use_best_model": True,
    "eval_metric": "NDCG:top=1",
}
