# Format: betfair_name: rpscrape_canonical_name

aint: Aintree
aintree: Aintree
ascot: Ascot
ayr: Ayr
ballin: Ballinrobe
ballinrobe: Ballinrobe
bang: Bangor
bangor-on-dee: Bangor-on-Dee
bath: Bath
belle: Bellewstown
bellewstown: Bellewstown
bev: Beverley
beverley: Beverley
brig: Brighton
brighton: Brighton
carl: Carlisle
carlisle: Carlisle
cart: Cartmel
cartmel: Cartmel
catt: Catterick
catterick: Catterick
chelmc: Chelmsford
chelmsford: Chelmsford
chelt: Cheltenham
cheltenham: Cheltenham
chep: Chepstow
chepstow: Chepstow
ches: Chester
chest: Chester
chester: Chester
chms: Chelmsford
clon: Clonmel
clonmel: Clonmel
cork: Cork
curr: Curragh
curragh: Curragh
donc: Doncaster
doncaster: Doncaster
down royal: Down Royal
downp: Downpatrick
downpatrick: Downpatrick
downr: Down Royal
dund: Dundalk
dundalk: Dundalk
epso: Epsom
epsm: Epsom
epsom: Epsom
extr: Exeter
exeter: Exeter
fairy: Fairyhouse
fairyhouse: Fairyhouse
fake: Fakenham
fakenham: Fakenham
ffos: Ffos Las
ffos las: Ffos Las
ffosl: Ffos Las
folk: Folkestone
font: Fontwell
fontwell: Fontwell
gal: Galway
galway: Galway
good: Goodwood
goodwood: Goodwood
gowp: Gowran Park
gowran park: Gowran Park
ham: Hamilton
hamilton: Hamilton
hayd: Haydock
haydock: Haydock
here: Hereford
hex: Hexham
hexham: Hexham
hexm: Hexham
hunt: Huntingdon
huntingdon: Huntingdon
kelso: Kelso
kemp: Kempton
kempton: Kempton
kilb: Kilbeggan
kilbeggan: Kilbeggan
killar: Killarney
killarney: Killarney
layt: Laytown
laytown: Laytown
leic: Leicester
leicester: Leicester
leop: Leopardstown
leopardstown: Leopardstown
lim: Limerick
limerick: Limerick
ling: Lingfield
lingfield: Lingfield
lngf: Lingfield
list: Listowel
listowel: Listowel
ludl: Ludlow
ludlow: Ludlow
market rasen: Market Rasen
mrktr: Market Rasen
muss: Musselburgh
musselburgh: Musselburgh
naas: Naas
navan: Navan
newb: Newbury
newbury: Newbury
newc: Newcastle
newcastle: Newcastle
newm: Newmarket
newmarket: Newmarket
newt: Newton Abbot
newton abbot: Newton Abbot
nmkt: Newmarket
nott: Nottingham
nottingham: Nottingham
perth: Perth
plum: Plumpton
plump: Plumpton
plumpton: Plumpton
pont: Pontefract
ponte: Pontefract
pontefract: Pontefract
punch: Punchestown
punchestown: Punchestown
redc: Redcar
redcar: Redcar
ripo: Ripon
ripon: Ripon
rosc: Roscommon
roscommon: Roscommon
sali: Salisbury
salis: Salisbury
salisbury: Salisbury
sand: Sandown
sandown: Sandown
sedge: Sedgefield
sedgefield: Sedgefield
sligo: Sligo
southwell: Southwell
sthl: Southwell
strat: Stratford
stratford: Stratford
taun: Taunton
taunton: Taunton
thir: Thirsk
thirsk: Thirsk
thurl: Thurles
thurles: Thurles
tipp: Tipperary
tipperary: Tipperary
towe: Towcester
towc: Towcester
towcester: Towcester
tram: Tramore
tramore: Tramore
uttx: Uttoxeter
uttox: Uttoxeter
uttoxeter: Uttoxeter
warw: Warwick
warwick: Warwick
weth: Wetherby
wetherby: Wetherby
wex: Wexford
wexford: Wexford
winc: Wincanton
wincanton: Wincanton
wins: Wincanton
wind: Windsor
windsor: Windsor
wolv: Wolverhampton
wolverhampton: Wolverhampton
worc: Worcester
worcester: Worcester
yarm: Yarmouth
yarmouth: Yarmouth
york: York
