CREATE TABLE IF NOT EXISTS races (
    race_id VARCHAR PRIMARY KEY,
    source_race_id VARCHAR,
    course_id VARCHAR NOT NULL,
    course_name VARCHAR NOT NULL,
    race_date DATE NOT NULL,
    scheduled_off_utc TIMESTAMPTZ NOT NULL,
    distance_furlongs FLOAT,
    going_code VARCHAR,
    going_description VARCHAR,
    race_type VARCHAR,
    race_class INTEGER,
    race_grade VARCHAR,
    prize_money_gbp FLOAT,
    field_size INTEGER,
    is_standard_race BOOLEAN DEFAULT TRUE,
    is_handicap BOOLEAN,
    surface VARCHAR,
    country VARCHAR DEFAULT 'GB',
    event_timestamp_utc TIMESTAMPTZ NOT NULL,
    decision_cutoff_utc TIMESTAMPTZ NOT NULL,
    ingest_timestamp_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS runners (
    runner_id VARCHAR PRIMARY KEY,
    race_id VARCHAR NOT NULL REFERENCES races(race_id),
    horse_id VARCHAR NOT NULL,
    horse_name VARCHAR NOT NULL,
    trainer_id VARCHAR,
    trainer_name VARCHAR,
    jockey_id VARCHAR,
    jockey_name VARCHAR,
    match_type VARCHAR,
    draw INTEGER,
    weight_lbs FLOAT,
    age INTEGER,
    official_rating INTEGER,
    headgear VARCHAR,
    headgear_first_time BOOLEAN DEFAULT FALSE,
    days_since_last_run INTEGER,
    career_runs INTEGER,
    event_timestamp_utc TIMESTAMPTZ NOT NULL,
    decision_cutoff_utc TIMESTAMPTZ NOT NULL,
    ingest_timestamp_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS results (
    result_id VARCHAR PRIMARY KEY,
    race_id VARCHAR NOT NULL REFERENCES races(race_id),
    runner_id VARCHAR NOT NULL REFERENCES runners(runner_id),
    horse_id VARCHAR NOT NULL,
    finishing_position INTEGER,
    finishing_position_raw VARCHAR,
    btn_lengths FLOAT,
    official_time_secs FLOAT,
    sp_decimal FLOAT,
    won BOOLEAN NOT NULL,
    event_timestamp_utc TIMESTAMPTZ NOT NULL,
    decision_cutoff_utc TIMESTAMPTZ NOT NULL,
    ingest_timestamp_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS odds_snapshots (
    snapshot_id VARCHAR PRIMARY KEY,
    race_id VARCHAR NOT NULL,
    runner_id VARCHAR NOT NULL,
    runner_name VARCHAR,
    source VARCHAR NOT NULL,
    market_type VARCHAR NOT NULL,
    snapshot_timestamp_utc TIMESTAMPTZ NOT NULL,
    snapshot_label VARCHAR,
    minutes_to_off INTEGER,
    decimal_odds FLOAT NOT NULL,
    implied_prob_raw FLOAT,
    traded_volume_gbp FLOAT,
    market_status VARCHAR,
    event_timestamp_utc TIMESTAMPTZ NOT NULL,
    decision_cutoff_utc TIMESTAMPTZ NOT NULL,
    ingest_timestamp_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS horse_history (
    history_id VARCHAR PRIMARY KEY,
    horse_id VARCHAR NOT NULL,
    horse_name VARCHAR NOT NULL,
    race_id VARCHAR NOT NULL,
    race_date DATE NOT NULL,
    scheduled_off_utc TIMESTAMPTZ NOT NULL,
    course_id VARCHAR,
    distance_furlongs FLOAT,
    going_code VARCHAR,
    race_type VARCHAR,
    race_class INTEGER,
    is_handicap BOOLEAN,
    field_size INTEGER,
    finishing_position INTEGER,
    won BOOLEAN,
    btn_lengths FLOAT,
    trainer_id VARCHAR,
    jockey_id VARCHAR,
    weight_lbs FLOAT,
    official_rating INTEGER,
    headgear VARCHAR,
    days_since_prev_run INTEGER,
    event_timestamp_utc TIMESTAMPTZ NOT NULL,
    decision_cutoff_utc TIMESTAMPTZ NOT NULL,
    ingest_timestamp_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS trainer_history (
    history_id VARCHAR PRIMARY KEY,
    trainer_id VARCHAR NOT NULL,
    trainer_name VARCHAR NOT NULL,
    race_id VARCHAR NOT NULL,
    race_date DATE NOT NULL,
    scheduled_off_utc TIMESTAMPTZ NOT NULL,
    course_id VARCHAR,
    race_type VARCHAR,
    going_code VARCHAR,
    distance_furlongs FLOAT,
    race_class INTEGER,
    days_since_last_run INTEGER,
    won BOOLEAN NOT NULL,
    finishing_position INTEGER,
    field_size INTEGER,
    event_timestamp_utc TIMESTAMPTZ NOT NULL,
    decision_cutoff_utc TIMESTAMPTZ NOT NULL,
    ingest_timestamp_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jockey_history (
    history_id VARCHAR PRIMARY KEY,
    jockey_id VARCHAR NOT NULL,
    jockey_name VARCHAR NOT NULL,
    trainer_id VARCHAR,
    race_id VARCHAR NOT NULL,
    race_date DATE NOT NULL,
    scheduled_off_utc TIMESTAMPTZ NOT NULL,
    course_id VARCHAR,
    race_type VARCHAR,
    going_code VARCHAR,
    won BOOLEAN NOT NULL,
    finishing_position INTEGER,
    field_size INTEGER,
    event_timestamp_utc TIMESTAMPTZ NOT NULL,
    decision_cutoff_utc TIMESTAMPTZ NOT NULL,
    ingest_timestamp_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
